nodeLinker: pnp

packageExtensions:
  "@apollo/client@*":
    dependencies:
      graphql: "*"
  "@apollographql/apollo-tools@*":
    dependencies:
      graphql: "*"
  "@webpack-cli/serve@*":
    dependencies:
      webpack-dev-server: "*"
  eslint@*:
    dependencies:
      js-yaml: "*"
  rc-animate@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-cascader@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-checkbox@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-collapse@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-dialog@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-input-number@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-menu@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-progress@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-rate@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-tabs@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-tooltip@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-trigger@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-upload@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-util@*:
    dependencies:
      react: "*"
      react-dom: "*"
  react-dom@*:
    dependencies:
      react: "*"
  webpack-dev-server@*:
    dependencies:
      webpack: "*"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
