name: Release
on:
  release:
    types:
      - published

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: pnpm install
        run: pnpm install --frozen-lockfile
      - name: pnpm build
        run: pnpm build
      # --no-verify-access to use automation tokens https://github.com/lerna/lerna/issues/2788
      # --ignore-scripts to avoid scripts that could read npm token
      # --yes to autoconfirm in ci
      # --pre-dist-tag do not tag prereleases as latest
      - name: publish to npm
        run: pnpm lerna:publish --ignore-scripts --yes --no-verify-access --pre-dist-tag rc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
