name: Test Pull Requests

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: Build packages
        run: yarn build

      - name: Test packages
        run: yarn test --ignore='@lowdefy/engine' --ignore='@lowdefy/format' --ignore='@lowdefy/blocks-*' --ignore='@lowdefy/plugin-aws'

      - name: Upload coverage to codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: Upload coverage to codeclimate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageLocations: |
            ${{github.workspace}}/packages/**/coverage/lcov.info:lcov
        continue-on-error: true

  check-yarn-cache:
    name: Check yarn cache
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
      - name: Check yarn cache integrity
        run: yarn install --immutable --immutable-cache --check-cache
