name: Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
      - name: Install and build
        run: pnpm install --frozen-lockfile
      - name: Test packages
        run: pnpm test
      - name: Upload coverage to codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Upload coverage to codeclimate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageLocations: |
            ${{github.workspace}}/packages/**/coverage/lcov.info:lcov
